name: Mobile-Detect

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: ['devel']
  pull_request:
    branches: [ $default-branch ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['5.3', '7.4']
        phpunit-versions: ['latest']
        composer-versions: ['latest']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '5.3'
            phpunit-versions: '4.8.36'
            composer-versions: 'v1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: phpunit:${{ matrix.phpunit-versions }}, composer:${{ matrix.composer-versions }}

      - name: Versions
        run: |
          php -v
          phpunit --version
          composer -V
        shell: bash

      - name: Run tests
        run: phpunit -v -c tests/phpunit.xml --coverage-text --strict-coverage --stop-on-risky
        shell: bash
